# Caching time for heads. The time must be specified in seconds
# Note: I recommend using a value from 1800 (30 minutes) to 10800 (3 hours).
cache-time: 1800
# The site that will be used to get the players' heads. Heads must be 8 pixels.
# Sites I recommend: mc-heads.net, crafthead.net minotar.net
heads-provider: 'https://minotar.net/helm/%s/8.png'

# Configure a resource pack
resource-pack:
  # Should the plugin suggest to load the resource pack when the player joins the server?
  enabled: true

  # URL where the resource pack can be downloaded
  url: https://www.dropbox.com/s/uc2epfgztrw8mvz/HeadsAnywhere.zip?dl=1

  # Should the plugin sent messages?
  messaging: false
  # Should the plugin kick the player when they decline the resource pack or if the resource pack download fails?
  kick-player: true

  # The message to be sent if the resource pack is successfully loaded
  successfully-loaded: '§aResource pack successfully loaded!'
  # The message to be sent if the download fails.
  failed-download: '§cFailed to download the resource pack. Please, contact the staff!'
  # The message to be sent if the player declined the resource pack
  declined: '§cYou need to accept the resource pack to play on the server!'