# Caching time for heads. The time must be specified in seconds
cache-time: 300

# Configure a resource pack
resource-pack:
  # Should the plugin suggest to load the resource pack when the player joins the server?
  enabled: true

  # URL where the resource pack can be downloaded
  url: https://www.dropbox.com/s/uc2epfgztrw8mvz/HeadsAnywhere.zip?dl=1
  
  # Should the plugin sent messages?
  messaging: false
  # The message to be sent if the resource pack is successfully loaded
  successfully-loaded: '§aResource pack successfully loaded!'
  # The message to be sent if the download fails
  failed-download: '§cFailed to download the resource pack. Please, contact the staff!'